### PR TITLE
Keep previous physics when entering/leaving sprint

### PR DESCRIPTION
**Pull request by ronoaldo**
Prevent losing the 3d_armor or mobs_nether speed/jump
changes from their boots.

### CODE REVIEW

**Comment by appgurueu** [comment]
Something like player monoids should be used. This is still buggy if another mod changes physics while you are sprinting.

**Comment by ronoaldo** [comment]
I tested with player_monoids and it was causing a funny effect of exponential speed bump when combined with the 3d_armor mod. This change made both cooperate better without it. How would I got to debug the 3d_armor x hbsprint x player_monoids interaction? It could also be another mod but if you run a local copy of my server build it should be easy to reproduce adding the player_monoids from contentdb.

**Comment by SmallJoker** [comment]
> How would I got to debug the 3d_armor x hbsprint x player_monoids interaction?

This would be a total pain until https://github.com/minetest/minetest/pull/10731 (or a comparable PR) is merged, and all mods updated accordingly. I highly doubt this is solvable without adding optional dependencies (at least for player_monoids), so that the physics override can be done using a single API rather than overriding each other.

**Comment by ronoaldo** [comment]
Thank you both for the clarification on the issue I was facing. I'll close the PR as it will not actually fix anything lol.

I'll keep my fork used at my server for now. If I manage to have a proper fix/solution or if I find something when I come back to player_monoids again, I'll open another discussion.

Thanks for the help!

**Pull request closed without merging**
